import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/common/app-sidebar";
import { ReactQueryProvider } from "@/components/providers/react-query-provider";

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-light-nutral text-zinc-100`}
        cz-shortcut-listen="true"
      >
        {/* Layout Shell */}
        <ReactQueryProvider>
          <SidebarProvider>
            {/* Sidebar */}
            <AppSidebar />

            {/* Main Content */}
            <main className="w-full pt-4 gap-3.5">
              <div className="ps-3.5">{children}</div>
            </main>
          </SidebarProvider>
        </ReactQueryProvider>
        {/* Footer */}
        {/* <Footer /> */}
      </body>
    </html>
  );
}


